#!/usr/bin/env bash

notify_volume () {
	MUTED=$(pamixer --get-mute)
	VOLUME=$(pamixer --get-volume)

	MESSAGE="Volume"
	ICON="/usr/share/icons/Flat-Remix-Black-Dark/status/scalable/512/notification-audio-volume-high.svg"
	LEVEL=0
	TIME_OUT=800

	if [[ "$MUTED" == "true" || "$VOLUME" == "0" ]]; then
		ICON="/usr/share/icons/Flat-Remix-Black-Dark/status/scalable/512/notification-audio-volume-muted.svg"
		MESSAGE="Muted"
		LEVEL=2
	elif [ "$VOLUME" -lt "40" ]; then
		ICON="/usr/share/icons/Flat-Remix-Black-Dark/status/scalable/512/notification-audio-volume-low.svg"
	elif [ "$VOLUME" -lt "70" ]; then
		ICON="/usr/share/icons/Flat-Remix-Black-Dark/status/scalable/512/notification-audio-volume-medium.svg"
	fi

	dunstify -r 442 -u $LEVEL -t $TIME_OUT -h int:value:$VOLUME -i $ICON $MESSAGE
}

notify_mic_mute () {
	MIC_MUTED=$(pamixer --get-mute --default-source)

	if [ "$MIC_MUTED" == "true" ]
	then
		dunstify -r 441 -u 2 -t 0 -i "/usr/share/icons/Flat-Remix-Black-Dark/status/scalable/512/notification-microphone-sensitivity-muted.svg" "Mic Off"
	else
		dunstify -r 441 -u 1 -t 500 -i "/usr/share/icons/Flat-Remix-Black-Dark/status/scalable/512/notification-microphone-sensitivity-high.svg" "Mic On"
	fi
}

case $1 in
	VOLUME_UP)
		if [ "$(pamixer --get-volume)" -lt "100" ]; then
			pactl set-sink-volume @DEFAULT_SINK@ +10%
		else
			pactl set-sink-volume @DEFAULT_SINK@ 100%
		fi
		notify_volume
		;;
	VOLUME_DOWN)
		pactl set-sink-volume @DEFAULT_SINK@ -10%
		notify_volume
		;;
	MUTE)
		pactl set-sink-mute @DEFAULT_SINK@ toggle
		notify_volume
		;;
	MIC_MUTE)
		pactl set-source-mute @DEFAULT_SOURCE@ toggle
		notify_mic_mute
		;;
esac
