#!/bin/bash
config_dir="$HOME/.config/hyprmonitor/configs"
modes=$(ls "$config_dir")
mode=$(printf "$modes" | rofi -dmenu -p "Display conf" -I)

readarray -t options < "$config_dir/$mode"

for opt in "${options[@]}"; do
	hyprctl keyword monitor "$opt"
done
