#!/bin/bash

case $XDG_SESSION_DESKTOP in
	i3)
		i3-msg restart
		;;
	herbstluftwm)
		herbstclient detect_monitors
		;;
	bspwm)
		$HOME/.config/bspwm/monitor_config
		;;
esac

sleep 0.5
nitrogen --restore
$HOME/.config/polybar/launch.sh
notify-send -i display "Display profile changed to ${AUTORANDR_CURRENT_PROFILE^}"

if touch_screen=$(xinput list --id-only "ELAN Touchscreen"); then
	xinput map-to-output $touch_screen eDP-1
fi
