#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/polybar/launch.sh

autorandr -c &

# picom --experimental-backends &
xset r rate 300 80 &

killall -q pa-applet
killall -q nm-applet
pa-applet --disable-key-grabbing --disable-notifications &
nm-applet &

$HOME/.config/bspwm/monitor_config

bspc config merge_overlapping_monitors true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config border_width         2
bspc config window_gap          10

bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config pointer_modifier mod1
bspc config focus_follows_pointer true


bspc rule -a Screenkey manage=off

bspc external_rules_command ~/.config/bspwm_external_rules

# bspc rule -a windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
# bspc rule -a windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
# bspc rule -a windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
# bspc rule -a fixedsize floating=on


