#!/usr/bin/env bash

# Multi monitor support. Needs MONITOR environment variable to be set for each instance of polybar
# If MONITOR environment variable is not set this will default to monitor 0
# Check https://github.com/polybar/polybar/issues/763
MON_IDX="0"
mapfile -t MONITOR_LIST < <(polybar --list-monitors | cut -d":" -f1)
for (( i=0; i<$((${#MONITOR_LIST[@]})); i++ )); do
  [[ ${MONITOR_LIST[${i}]} == "$MONITOR" ]] && MON_IDX="$i"
done;

herbstclient --idle "tag_*" 2>/dev/null | {

    while true; do
        # Read tags into $tags as array
        IFS=$'\t' read -ra tags <<< "$(herbstclient tag_status "${MON_IDX}")"
        {
			echo "%{O5}"
            for i in "${tags[@]}" ; do
                # focus the monitor of the current bar before switching tags
                echo "%{A1:herbstclient focus_monitor ${MON_IDX}; herbstclient use ${i:1}:}"

                case ${i:0:1} in
                    '.')
                        # the tag is empty
						echo "%{F#00000000}%{T4}%{F#eeff96}"
                        ;;
                    ':')
                        # the tag is not empty
						echo "%{F#594671}%{T4}%{F#eeff96}"
                        ;;
                    '+')
                        # the tag is viewed on the specified MONITOR, but this monitor is not focused.
						echo "%{F#aac0cb47}%{T4}%{F#eeff96}"
                        ;;
                    '#')
                        # the tag is viewed on the specified MONITOR and it is focused.
						echo "%{F#d9ed00}%{T4}%{F#292640}"
                        ;;
                    '-')
                        # the tag is viewed on a different MONITOR, but this monitor is not focused.
						echo "%{F#aa77c6a9}%{T4}%{F#eeff96}"
                        ;;
                    '%')
                        # the tag is viewed on a different MONITOR and it is focused.
						echo "%{F#53e0ad}%{T4}%{F#292640}"
                        ;;
                    '!')
                        # the tag contains an urgent window
						echo "%{F#e03d3d}%{T4}%{F#eeff96}"
                        ;;
                esac

                echo "%{O-14 T-}${i:1}%{A -u -o F- B- O10}"
            done

            # reset foreground and background color to default
            echo "%{F-}%{B-}"
        } | tr -d "\n"

    echo

    # wait for next event from herbstclient --idle
    read -r || break
done
} 2>/dev/null
